api_platform:
    enable_swagger: true       # active la génération du fichier OpenAPI
    enable_swagger_ui: true    # active Swagger UI (/api)

    openapi:
        contact:
            name: 'Esportify'
            email: 'email@exemple.com'
            url: ''
        license:
            name: 'MIT'
            url: 'https://opensource.org/licenses/MIT'
        termsOfService: 'https://ton-site.com/terms'
