nelmio_api_doc:
    documentation:
        info:
            title: 'My API'
            description: 'API documentation with Nelmio and Symfony'
            version: '1.0.0'
    areas:
        path_patterns:
            - ^/api(?!/docs)
            