#index:
#    path: /
#    controller: App\Controller\DefaultController::index
frontend:
    path: /{reactRouting}
    controller: App\Controller\FrontendController::index
    requirements:
        reactRouting: ".+"
