services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
        autowire: true
        autoconfigure: true

    serializer.normalizer.object.inner:
        alias: 'serializer.normalizer.object'
        public: false

    App\Serializer\UserNormalizer:
        decorates: 'serializer.normalizer.object'
        decoration_priority: 5
        arguments:
            $normalizer: '@serializer.normalizer.object.inner'
        autowire: true
        autoconfigure: false
        public: false

    App\Serializer\EvenementsNormalizer:
        arguments:
            $normalizer: '@serializer.normalizer.object.inner'
        tags: ['serializer.normalizer']

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
